# Generated by Django 3.0.7 on 2020-12-01 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0028_auto_20201111_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_enroll_time',
            field=models.DateTimeField(default=datetime.datetime(2199, 1, 1, 0, 0, tzinfo=utc), null=True, verbose_name='End Date and Time for enrollment of contest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_enroll_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start Date and Time for enrollment of contest'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='allow_skip',
            field=models.BooleanField(default=True, verbose_name='Allow members to skip questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Instructions for Members'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='view_answerpaper',
            field=models.BooleanField(default=False, verbose_name='Allow member to view their answer                                            paper'),
        ),
    ]
